(function () {
  const heroImage = 'assets/images/dj-too-kold-hero-1400.jpg';
  const thumbImage = 'assets/images/dj-too-kold-thumb-720.jpg';

  const mediaItems = [
    {
      id: 'blue-hour-dance-floor',
      title: 'Blue Hour Dance Floor',
      description: 'A packed-room visual for the late-night section of a private event.',
      mediaType: 'photos',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '2026-04-18',
      venue: 'Private event room',
      tags: ['nightlife', 'dance floor', 'featured'],
      featured: true,
      displayOrder: 10,
      sourceType: 'local',
      storageBucket: 'public-media',
      storagePath: 'gallery/blue-hour-dance-floor.webp',
      externalUrl: '',
      embedUrl: '',
      provider: '',
      altText: 'Blue-lit DJ booth with a live Birmingham event crowd',
      layout: 'large'
    },
    {
      id: 'crowd-call-clip',
      title: 'Crowd Call Clip',
      description: 'A short video moment built for social recap posts and booking proof.',
      mediaType: 'videos',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '2026-03-29',
      venue: 'Downtown celebration',
      tags: ['video', 'recap', 'crowd'],
      featured: false,
      displayOrder: 20,
      sourceType: 'external',
      storageBucket: '',
      storagePath: '',
      externalUrl: '',
      embedUrl: '',
      provider: 'youtube',
      altText: 'DJ booth lighting during a crowd response moment at an Alabama event',
      layout: 'wide'
    },
    {
      id: 'weekend-party-flyer',
      title: 'Weekend Party Flyer',
      description: 'Promo artwork sized for quick event announcements and social sharing.',
      mediaType: 'flyers',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '2026-03-08',
      venue: 'Promo release',
      tags: ['flyer', 'promo', 'party'],
      featured: false,
      displayOrder: 30,
      sourceType: 'local',
      storageBucket: 'public-media',
      storagePath: 'flyers/weekend-party-flyer.webp',
      externalUrl: '',
      embedUrl: '',
      provider: '',
      altText: 'DJ Too Kold promotional artwork with blue event lighting',
      layout: ''
    },
    {
      id: 'reception-energy-recap',
      title: 'Reception Energy Recap',
      description: 'A post-event recap card focused on smooth pacing and a strong dance floor.',
      mediaType: 'event_recaps',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '2026-02-22',
      venue: 'Wedding reception',
      tags: ['wedding', 'recap', 'dance floor'],
      featured: true,
      displayOrder: 40,
      sourceType: 'local',
      storageBucket: 'public-media',
      storagePath: 'recaps/reception-energy-recap.webp',
      externalUrl: '',
      embedUrl: '',
      provider: '',
      altText: 'DJ setup with blue and white lights during a wedding reception',
      layout: 'tall'
    },
    {
      id: 'clean-setup-venue-shot',
      title: 'Clean Setup Venue Shot',
      description: 'Venue-ready booth placement with lighting that keeps the room polished.',
      mediaType: 'venue_shots',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '2026-02-10',
      venue: 'Banquet hall',
      tags: ['venue', 'setup', 'lighting'],
      featured: false,
      displayOrder: 50,
      sourceType: 'local',
      storageBucket: 'public-media',
      storagePath: 'venues/clean-setup-venue-shot.webp',
      externalUrl: '',
      embedUrl: '',
      provider: '',
      altText: 'DJ gear and lighting arranged for an indoor Alabama event',
      layout: ''
    },
    {
      id: 'too-kold-promo-image',
      title: 'Too Kold Promo Image',
      description: 'Brand-forward image for flyers, homepage callouts, and social posts.',
      mediaType: 'promo_images',
      fileUrl: heroImage,
      thumbnailUrl: thumbImage,
      eventDate: '',
      venue: 'Project Neo media kit',
      tags: ['brand', 'promo', 'press'],
      featured: false,
      displayOrder: 60,
      sourceType: 'local',
      storageBucket: 'public-media',
      storagePath: 'promo/too-kold-promo-image.webp',
      externalUrl: '',
      embedUrl: '',
      provider: '',
      altText: 'DJ Too Kold brand image with blue stage lighting',
      layout: 'wide'
    }
  ];

  const mixes = [
    {
      id: 'icebreaker-party-set',
      title: 'Icebreaker Party Set',
      description: 'Hip-hop, R&B, Afrobeats, dance classics, and current crowd movers blended for social events.',
      mediaType: 'mixes',
      mixType: 'Party mix',
      fileUrl: '',
      audioUrl: '',
      embedUrl: '',
      externalUrl: '',
      thumbnailUrl: thumbImage,
      coverImageUrl: heroImage,
      eventDate: '',
      venue: 'Studio preview',
      durationSeconds: 1320,
      platform: 'Native audio',
      tags: ['party', 'hip-hop', 'r&b'],
      featured: true,
      displayOrder: 10,
      sourceType: 'external',
      provider: 'soundcloud',
      altText: 'DJ Too Kold party mix cover with stage lighting'
    },
    {
      id: 'prom-night-pressure',
      title: 'Prom Night Pressure',
      description: 'School-safe energy with familiar hooks, clean edits, and quick transitions for student events.',
      mediaType: 'mixes',
      mixType: 'Clean edit sample',
      fileUrl: '',
      audioUrl: '',
      embedUrl: '',
      externalUrl: '',
      thumbnailUrl: thumbImage,
      coverImageUrl: heroImage,
      eventDate: '',
      venue: 'Clean mix preview',
      durationSeconds: 1080,
      platform: 'Native audio',
      tags: ['school events', 'clean edits', 'prom'],
      featured: false,
      displayOrder: 20,
      sourceType: 'external',
      provider: 'mixcloud',
      altText: 'DJ lighting and booth cover art for a clean school event mix'
    },
    {
      id: 'reception-glow-up',
      title: 'Reception Glow-Up',
      description: 'A smooth path from dinner atmosphere into dance floor records without rushing the room.',
      mediaType: 'mixes',
      mixType: 'Wedding transition',
      fileUrl: '',
      audioUrl: '',
      embedUrl: '',
      externalUrl: '',
      thumbnailUrl: thumbImage,
      coverImageUrl: heroImage,
      eventDate: '',
      venue: 'Wedding preview',
      durationSeconds: 1560,
      platform: 'Native audio',
      tags: ['wedding', 'transition', 'reception'],
      featured: true,
      displayOrder: 30,
      sourceType: 'external',
      provider: 'spotify',
      altText: 'Wedding reception lighting and DJ booth cover art'
    }
  ];

  window.ProjectNeoMediaData = {
    mediaItems,
    mixes,
    schema: {
      fields: [
        'title',
        'description',
        'mediaType',
        'fileUrl',
        'thumbnailUrl',
        'eventDate',
        'venue',
        'tags',
        'featured',
        'displayOrder'
      ],
      storageFields: ['sourceType', 'storageBucket', 'storagePath', 'externalUrl', 'embedUrl', 'provider']
    }
  };
})();
