[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  PROJECT_NEO_ENV = "production"

[context.deploy-preview.environment]
  PROJECT_NEO_ENV = "staging"

[context.branch-deploy.environment]
  PROJECT_NEO_ENV = "staging"

[[headers]]
  for = "/admin-login.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/admin-dashboard.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/client-portal.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
